// Generated by CoffeeScript 1.10.0
var destination, options, request;

request = require("request");

request('http://www.google.com', function(error, response, body) {
  if (!error && response.statusCode === 200) {
    return console.log(body);
  }
});

options = {
  url: "http://google.com",
  qs: {}
};

request(options, function(error, response, body) {});

destination = fs.createWriteStream('./google.html');

request("http://google.com").pipe(destination);
