// Generated by CoffeeScript 1.9.3
var AdmZip, willSendthis, zip, zipEntries;

AdmZip = require('adm-zip');

zip = new AdmZip('./my_file.zip');

zipEntries = zip.getEntries();

zipEntries.forEach(function(zipEntry) {
  console.log(zipEntry.toString());
  if (zipEntry.entryName === 'my_file.txt') {
    console.log(zipEntry.data.toString('utf8'));
  }
});

console.log(zip.readAsText('some_folder/my_file.txt'));

zip.extractEntryTo('some_folder/my_file.txt', '/home/me/tempfolder', false, true);

zip.extractAllTo('/home/me/zipcontent/', true);

zip = new AdmZip;

zip.addFile('test.txt', new Buffer('inner content of the file'), 'entry comment goes here');

zip.addLocalFile('/home/me/some_picture.png');

willSendthis = zip.toBuffer();

zip.writeZip('/home/me/files.zip');
